CREATE OR REPLACE DATABASE RETAIL_DB;
USE DATABASE RETAIL_DB;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA MART;

CREATE ROLE DBT_ANALYST_ROLE COMMENT = 'Role for DBT_ANALYST';

-- Grant USAGE privilege on a warehouse
GRANT USAGE ON WAREHOUSE compute_wh TO ROLE DBT_ANALYST_ROLE;

-- Grant USAGE privilege on a database
GRANT USAGE ON DATABASE RETAIL_DB TO ROLE DBT_ANALYST_ROLE;

-- Grant create and usage privilege on all tables in a schema
GRANT USAGE, CREATE TABLE, CREATE VIEW, MODIFY ON ALL SCHEMAS IN DATABASE RETAIL_DB TO ROLE DBT_ANALYST_ROLE;
-- For future objects
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE RETAIL_DB TO ROLE DBT_ANALYST_ROLE;



CREATE USER DBT_USER
  PASSWORD = '****************'
  LOGIN_NAME = 'DBT_USER'
  EMAIL = 'DBT_USER@example.com'
  DEFAULT_ROLE = DBT_ANALYST_ROLE
  MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE DBT_ANALYST_ROLE TO USER DBT_USER;

