USE RAW;
CREATE OR REPLACE STAGE RAW.RETAIL_STAGE;

-- File format
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER = 1;

-- Load Customers
COPY INTO RAW.CUSTOMERS FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"');

/*
COPY INTO RAW.CUSTOMERS FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = CSV_FORMAT;
*/

-- Load Products
COPY INTO RAW.PRODUCTS FROM @RETAIL_STAGE/products.csv
FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1);

/*
COPY INTO RAW.PRODUCTS
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = CSV_FORMAT;
*/

-- Load Orders
COPY INTO RAW.ORDERS FROM @RETAIL_STAGE/orders.csv
FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1);

/*
COPY INTO RAW.ORDERS
FROM @RETAIL_STAGE/orders.csv
FILE_FORMAT = CSV_FORMAT;
*/

-- Load Order Items
COPY INTO RAW.ORDER_ITEMS FROM @RETAIL_STAGE/order_items.csv
FILE_FORMAT=(TYPE=CSV SKIP_HEADER=1);

/*
COPY INTO RAW.ORDER_ITEMS
FROM @RETAIL_STAGE/order_items.csv
FILE_FORMAT = CSV_FORMAT;
*/